import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Auditorium from '../models/Auditorium.js';

dotenv.config();

const auditoriumsData = [
    // educacion continua
    {
        code: "EC-2.1",
        name: "Salón EC-2.1",
        floor: 2,
        capacity: 30,
        countedSeats: 28,
        comments: "Deberia ser para 28",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "No tiene",
        chairType: "No tiene",
        boardType: "No tiene",
        equipment: "No tiene",
        outlets: "No tiene",
        mobility: "Limitada",
        environment: "OK",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "Disponible",
        usableForReservations: false
    },
    {
        code: "EC-2.2",
        name: "Salón EC-2.2",
        floor: 2,
        capacity: 30,
        countedSeats: 30,
        comments: "OK 30",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "No tiene",
        chairType: "No tiene",
        boardType: "No tiene",
        equipment: "No tiene",
        outlets: "No tiene",
        mobility: "Limitada",
        environment: "OK",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "Disponible",
        usableForReservations: false
    },
    {
        code: "EC-2.3",
        name: "Salón EC-2.3",
        floor: 2,
        capacity: 30,
        countedSeats: 30,
        comments: "OK 30",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Limitada",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EC-2.4",
        name: "Salón EC-2.4",
        floor: 2,
        capacity: 30,
        countedSeats: 30,
        comments: "OK 30",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Limitada",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EC-3.1",
        name: "Salón EC-3.1",
        floor: 3,
        capacity: 35,
        countedSeats: 37,
        comments: "OK 35",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Limitada",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EC-3.2",
        name: "Salón EC-3.2",
        floor: 3,
        capacity: 35,
        countedSeats: 36,
        comments: "Debería ser para 30",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Limitada",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EC-3.3",
        name: "Salón EC-3.3",
        floor: 3,
        capacity: 35,
        countedSeats: 37,
        comments: "Debería ser para 33",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Limitada",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EC-3.5",
        name: "Salón EC-3.5",
        floor: 3,
        capacity: 35,
        countedSeats: 26,
        comments: "Debería ser para 30",
        characteristic: "Aula Especial",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Limitada",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EC-A1-A2",
        name: "Salón EC-A1-A2",
        floor: 3,
        capacity: 100,
        countedSeats: 88,
        comments: "Espacio abierto unificado",
        characteristic: "Auditorio Grande",
        type: "Plano",
        tableType: "No Aplica",
        chairType: "Fijas",
        boardType: "Fijo",
        equipment: "Proyector y Sonido",
        outlets: "Tiene",
        mobility: "Buena",
        environment: "Muy bueno",
        reservationContact: "reservasmultimedios@unicatolica.edu.co",
        status: "Disponible",
        usableForReservations: true
    },

    // Almendros
    {
        code: "ALM_3.1",
        name: "Salón ALM_3.1",
        floor: 3,
        capacity: 33,
        countedSeats: 35,
        comments: "Pueden ser 35",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM_3.10",
        name: "Salón ALM_3.10",
        floor: 3,
        capacity: 40,
        countedSeats: 38,
        comments: "Deberia ser para 38",
        characteristic: "Plano-MesaFija-SillaMovil (65)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM_3.11",
        name: "Salón ALM_3.11",
        floor: 3,
        capacity: 40,
        countedSeats: 40,
        comments: "OK 40",
        characteristic: "Plano-MesaFija-SillaMovil (65)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "Ruido cuarto de aire",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM_3.2",
        name: "Salón ALM_3.2",
        floor: 3,
        capacity: 40,
        countedSeats: 34,
        comments: "OK 40, falta una mesa",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "Ruido cuarto de aire",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM_3.3",
        name: "Salón ALM_3.3",
        floor: 3,
        capacity: 40,
        countedSeats: 35,
        comments: "Deberia ser para 35",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM_3.4",
        name: "Salón ALM_3.4",
        floor: 3,
        capacity: 40,
        countedSeats: 40,
        comments: "OK 40",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "Obras al lado",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "Bloqueado",
        usableForReservations: true
    },
    {
        code: "ALM_3.5",
        name: "Salón ALM_3.5",
        floor: 3,
        capacity: 40,
        countedSeats: 39,
        comments: "Deberia ser para 35",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "Obras al lado",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "Bloqueado",
        usableForReservations: true
    },
    {
        code: "ALM_3.6",
        name: "Salón ALM_3.6",
        floor: 3,
        capacity: 40,
        countedSeats: 36,
        comments: "OK 40, falta una mesa",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM_3.7",
        name: "Salón ALM_3.7",
        floor: 3,
        capacity: 36,
        countedSeats: 36,
        comments: "OK 36",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "Sin aire",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM_3.8",
        name: "Salón ALM_3.8",
        floor: 3,
        capacity: 40,
        countedSeats: 39,
        comments: "OK 40, falta una silla",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "Sin aire",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM_3.9",
        name: "Salón ALM_3.9",
        floor: 3,
        capacity: 33,
        countedSeats: 25,
        comments: "Deberia ser para 25",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM-1.1",
        name: "Salón ALM-1.1",
        floor: 1,
        capacity: 35,
        countedSeats: 27,
        comments: "Hay 27 sillas y 16 mesas",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM-1.2",
        name: "Salón ALM-1.2",
        floor: 1,
        capacity: 35,
        countedSeats: 35,
        comments: "OK 35",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM-1.3",
        name: "Salón ALM-1.3",
        floor: 1,
        capacity: 40,
        countedSeats: 36,
        comments: "Deberia ser para 37",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo - Grande",
        equipment: "No funciona el micrófono",
        outlets: "Individual",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM-1.4",
        name: "Salón ALM-1.4",
        floor: 1,
        capacity: 40,
        countedSeats: 42,
        comments: "OK 40",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo - Grande",
        equipment: "Proyector",
        outlets: "Individual",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM-1.5",
        name: "Salón ALM-1.5",
        floor: 1,
        capacity: 40,
        countedSeats: 39,
        comments: "OK 40",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Móvil - Pequeño",
        equipment: "Proyector",
        outlets: "Individual",
        mobility: "Interior escalonado",
        environment: "Obras al lado",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM-1.6",
        name: "Salón ALM-1.6",
        floor: 1,
        capacity: 40,
        countedSeats: 30,
        comments: "OK 40",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Móvil - Pequeño",
        equipment: "Proyector",
        outlets: "Individual",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM-1.7",
        name: "Salón ALM-1.7",
        floor: 1,
        capacity: 40,
        countedSeats: 40,
        comments: "OK 40, hay una silla mala y una mesa sin sillas",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Móvil - Pequeño",
        equipment: "Proyector",
        outlets: "Individual",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "ALM-1.8",
        name: "Salón ALM-1.8",
        floor: 1,
        capacity: 40,
        countedSeats: 39,
        comments: "OK 40, hay 3 mesas sin sillas",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Móvil - Pequeño",
        equipment: "Proyector",
        outlets: "Individual",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "AUD_ALM.",
        name: "Auditorio Almendros",
        floor: 1,
        capacity: 202,
        countedSeats: 209,
        comments: "OK",
        characteristic: "Auditorio Almendros",
        type: "Auditorio",
        tableType: "Fija",
        chairType: "Fija",
        boardType: "No tiene",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },

    // Cedro Rosado
    {
        code: "CR-2.1",
        name: "Salón CR-2.1",
        floor: 2,
        capacity: 30,
        countedSeats: 28,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Tableta? - micrófono y teléfono",
        outlets: "Algunos tomas en la pared del fondo",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-3.1",
        name: "Salón CR-3.1",
        floor: 3,
        capacity: 30,
        countedSeats: 30,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Video Beam. PC, Camara Mic , Sonido Tv",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-3.2",
        name: "Salón CR-3.2",
        floor: 3,
        capacity: 30,
        countedSeats: null,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Video Beam. PC, Camara Mic , Sonido Tv",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-3.3",
        name: "Salón CR-3.3",
        floor: 3,
        capacity: 30,
        countedSeats: null,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Video Beam. PC, Camara Mic , Sonido Tv",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-3.4",
        name: "Salón CR-3.4",
        floor: 3,
        capacity: 30,
        countedSeats: null,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Video Beam. PC, Camara Mic , Sonido Tv",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-4.1",
        name: "Salón CR-4.1",
        floor: 4,
        capacity: 30,
        countedSeats: 27,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Tableta? - micrófono y teléfono",
        outlets: "Algunos tomas en la pared del fondo",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-4.2",
        name: "Salón CR-4.2",
        floor: 4,
        capacity: 30,
        countedSeats: 32,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Tableta? - micrófono y teléfono",
        outlets: "Algunos tomas en la pared del fondo",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-4.3",
        name: "Salón CR-4.3",
        floor: 4,
        capacity: 30,
        countedSeats: 28,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Tableta? - micrófono y teléfono",
        outlets: "Algunos tomas en la pared del fondo",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-4.4",
        name: "Salón CR-4.4",
        floor: 4,
        capacity: 30,
        countedSeats: 30,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Tableta? - micrófono y teléfono",
        outlets: "Algunos tomas en la pared del fondo",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-5.1",
        name: "Salón CR-5.1",
        floor: 5,
        capacity: 30,
        countedSeats: 28,
        comments: "Deberia ser para 28",
        characteristic: "Aula Especial",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "Tableta, clases Hibridas",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "CR-5.2",
        name: "Salón CR-5.2",
        floor: 5,
        capacity: 30,
        countedSeats: 30,
        comments: "OK 30",
        characteristic: "Aula Especial",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "Tableta, clases Hibridas",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "CR-5.3",
        name: "Salón CR-5.3",
        floor: 5,
        capacity: 30,
        countedSeats: 28,
        comments: "",
        characteristic: "Aula Especial",
        type: "Plano",
        tableType: "Móvil Para 2 Personas",
        chairType: "Móvil",
        boardType: "Móvil - Pequeño",
        equipment: "Tableta, clases Hibridas",
        outlets: "Individual",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-5.4",
        name: "Salón CR-5.4",
        floor: 5,
        capacity: 30,
        countedSeats: 28,
        comments: "OK 30",
        characteristic: "Aula Especial",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "Tableta, clases Hibridas",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "CR-6.2",
        name: "Salón CR-6.2",
        floor: 6,
        capacity: 30,
        countedSeats: 30,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Tableta? - micrófono y teléfono",
        outlets: "Algunos tomas en la pared del fondo",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-6.3",
        name: "Salón CR-6.3",
        floor: 6,
        capacity: 30,
        countedSeats: 28,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Tableta? - micrófono y teléfono",
        outlets: "Algunos tomas en la pared del fondo",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "CR-AU.1",
        name: "Auditorio Cedro Rosado 1",
        floor: 1,
        capacity: 90,
        countedSeats: 88,
        comments: "OK",
        characteristic: "Auditorio Cedro Rosado",
        type: "Auditorio",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "Sin teléfono ni micrófono",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "CR-AU.2",
        name: "Auditorio Cedro Rosado 2",
        floor: 1,
        capacity: 54,
        countedSeats: 53,
        comments: "",
        characteristic: "Auditorio Cedro Rosado",
        type: "Auditorio",
        tableType: "",
        chairType: "",
        boardType: "Fijo - Grande",
        equipment: "Vb-Pc-Sonv",
        outlets: "Individual",
        mobility: "Limitada",
        environment: "",
        reservationContact: "reservasmultimedios@",
        status: "",
        usableForReservations: true
    },
    {
        code: "CR-AU.3",
        name: "Auditorio Cedro Rosado 3",
        floor: 1,
        capacity: 54,
        countedSeats: 53,
        comments: "Tiene 53 puestos",
        characteristic: "Auditorio Cedro Rosado",
        type: "Auditorio",
        tableType: "Fija",
        chairType: "Fija",
        boardType: "Fijo - Grande",
        equipment: "Sin teléfono ni micrófono",
        outlets: "Individual",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    // Guayacanes
    {
        code: "EG-2.4",
        name: "Salón EG-2.4",
        floor: 2,
        capacity: 90,
        countedSeats: 90,
        comments: "OK 90, una mesa dañada",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 2 Personas",
        chairType: "Móvil",
        boardType: "Fijo y Móvil Pequeño",
        equipment: "Video Beam. PC, Camara Mic , Sonido Tv",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EG-3.1",
        name: "Salón EG-3.1",
        floor: 3,
        capacity: 25,
        countedSeats: 25,
        comments: "OK 25",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Video Beam. PC, Camara Mic , Sonido Tv",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EG-4.1",
        name: "Salón EG-4.1",
        floor: 4,
        capacity: 25,
        countedSeats: 25,
        comments: "OK 25",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Video Beam. PC, Camara Mic , Sonido Tv",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "EG-5.2",
        name: "Salón EG-5.2",
        floor: 5,
        capacity: 1,
        countedSeats: 31,
        comments: "OK 31",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Video Beam. PC, Camara Mic , Sonido Tv",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "Bloqueado",
        usableForReservations: false
    },

    // Guaduales
    {
        code: "GUADUALES1",
        name: "Salón GUADUALES1",
        floor: 1,
        capacity: 30,
        countedSeats: 32,
        comments: "OK 30",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "GUADUALES2",
        name: "Salón GUADUALES2",
        floor: 1,
        capacity: 30,
        countedSeats: 32,
        comments: "OK 30",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo y Móvil Pequeño",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },

    // Lago (continuación)
    {
        code: "LG-1.0",
        name: "Salón LG-1.0",
        floor: 1,
        capacity: 19,
        countedSeats: 19,
        comments: "unos 3 mas",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-1.2",
        name: "Salón LG-1.2",
        floor: 1,
        capacity: 40,
        countedSeats: 38,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-1.3",
        name: "Salón LG-1.3",
        floor: 1,
        capacity: 40,
        countedSeats: 39,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-1.4",
        name: "Salón LG-1.4",
        floor: 1,
        capacity: 40,
        countedSeats: 38,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-1.5",
        name: "Salón LG-1.5",
        floor: 1,
        capacity: 40,
        countedSeats: 44,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-1.6",
        name: "Salón LG-1.6",
        floor: 1,
        capacity: 40,
        countedSeats: 36,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-1.7",
        name: "Salón LG-1.7",
        floor: 1,
        capacity: 40,
        countedSeats: 41,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-1.8",
        name: "Salón LG-1.8",
        floor: 1,
        capacity: 40,
        countedSeats: 47,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-2.0",
        name: "Salón LG-2.0",
        floor: 2,
        capacity: 19,
        countedSeats: 23,
        comments: "Deberia ser para 18",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "Por fuera del edificio",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-2.12",
        name: "Salón LG-2.12",
        floor: 2,
        capacity: 19,
        countedSeats: 24,
        comments: "unos 3 mas",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "Por fuera del edificio",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-2.13",
        name: "Salón LG-2.13",
        floor: 2,
        capacity: 19,
        countedSeats: 21,
        comments: "OK 19",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "Por fuera del edificio",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-2.14",
        name: "Salón LG-2.14",
        floor: 2,
        capacity: 19,
        countedSeats: 20,
        comments: "OK 19",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "Por fuera del edificio",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-2.2",
        name: "Salón LG-2.2",
        floor: 2,
        capacity: 40,
        countedSeats: 38,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-2.6",
        name: "Salón LG-2.6",
        floor: 2,
        capacity: 19,
        countedSeats: 18,
        comments: "OK 19",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "proyector, telefono",
        outlets: "Tomas alrededor",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "LG-2.8",
        name: "Salón LG-2.8",
        floor: 2,
        capacity: 19,
        countedSeats: 23,
        comments: "OK 19",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-2.9",
        name: "Salón LG-2.9",
        floor: 2,
        capacity: 19,
        countedSeats: 21,
        comments: "OK 19",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Carritos chocones",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-3.1",
        name: "Salón LG-3.1",
        floor: 3,
        capacity: 40,
        countedSeats: 42,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-3.3",
        name: "Salón LG-3.3",
        floor: 3,
        capacity: 40,
        countedSeats: 34,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-3.4",
        name: "Salón LG-3.4",
        floor: 3,
        capacity: 40,
        countedSeats: 41,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-3.5",
        name: "Salón LG-3.5",
        floor: 3,
        capacity: 40,
        countedSeats: 37,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-4.0",
        name: "Salón LG-4.0",
        floor: 4,
        capacity: 40,
        countedSeats: 35,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-4.2",
        name: "Salón LG-4.2",
        floor: 4,
        capacity: 40,
        countedSeats: 38,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-4.3",
        name: "Salón LG-4.3",
        floor: 4,
        capacity: 40,
        countedSeats: 34,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-4.4",
        name: "Salón LG-4.4",
        floor: 4,
        capacity: 40,
        countedSeats: 36,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },
    {
        code: "LG-4.6",
        name: "Salón LG-4.6",
        floor: 4,
        capacity: 40,
        countedSeats: 37,
        comments: "OK 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "",
        boardType: "",
        equipment: "",
        outlets: "",
        mobility: "",
        environment: "",
        reservationContact: "Auto reservas  / reservasmultimedios@",
        status: "",
        usableForReservations: false
    },

    // Palmas (continuación)
    {
        code: "PL-1.3",
        name: "Salón PL-1.3",
        floor: 1,
        capacity: 50,
        countedSeats: 50,
        comments: "OK 50",
        characteristic: "Escalonado-SillaAuditorio (63)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "video bean, comp, sonido, mic, camara",
        outlets: "Individual",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "PL-1.4",
        name: "Salón PL-1.4",
        floor: 1,
        capacity: 50,
        countedSeats: 50,
        comments: "OK 50",
        characteristic: "Escalonado-SillaAuditorio (63)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "video bean, comp, sonido, mic, camara",
        outlets: "Individual",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "PL-1.5",
        name: "Salón PL-1.5",
        floor: 1,
        capacity: 50,
        countedSeats: 50,
        comments: "OK 50",
        characteristic: "Escalonado-SillaAuditorio (63)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "video bean, comp, sonido, mic, camara",
        outlets: "Individual",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "PL-1.6",
        name: "Salón PL-1.6",
        floor: 1,
        capacity: 50,
        countedSeats: 50,
        comments: "OK 50",
        characteristic: "Escalonado-SillaAuditorio (63)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "video bean, comp, sonido, mic, camara",
        outlets: "Individual",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },

    // Samán (continuación)
    {
        code: "SM-1.3",
        name: "Salón SM-1.3",
        floor: 1,
        capacity: 39,
        countedSeats: 39,
        comments: "OK 36",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-1.4",
        name: "Salón SM-1.4",
        floor: 1,
        capacity: 38,
        countedSeats: 35,
        comments: "OK 36",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-1.5",
        name: "Salón SM-1.5",
        floor: 1,
        capacity: 36,
        countedSeats: 41,
        comments: "OK 36",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-1.6",
        name: "Salón SM-1.6",
        floor: 1,
        capacity: 36,
        countedSeats: 34,
        comments: "OK 36",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-1.7",
        name: "Salón SM-1.7",
        floor: 1,
        capacity: 36,
        countedSeats: 35,
        comments: "OK 36",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-1.8",
        name: "Salón SM-1.8",
        floor: 1,
        capacity: 36,
        countedSeats: 35,
        comments: "OK 36",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-1.9",
        name: "Salón SM-1.9",
        floor: 1,
        capacity: 30,
        countedSeats: 30,
        comments: "OK 30",
        characteristic: "Escal-MesaFija-SillaMovil (62)",
        type: "Escalonado",
        tableType: "Fija",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Interior escalonado",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.2",
        name: "Salón SM-2.2",
        floor: 2,
        capacity: 50,
        countedSeats: 46,
        comments: "Deberia ser para 40",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.3",
        name: "Salón SM-2.3",
        floor: 2,
        capacity: 26,
        countedSeats: 27,
        comments: "Deberia ser para 21",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "Muy pequeño",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.4",
        name: "Salón SM-2.4",
        floor: 2,
        capacity: 30,
        countedSeats: 32,
        comments: "OK 30",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.5",
        name: "Salón SM-2.5",
        floor: 2,
        capacity: 34,
        countedSeats: 36,
        comments: "OK 34",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Dos tableros fijos",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.6",
        name: "Salón SM-2.6",
        floor: 2,
        capacity: 36,
        countedSeats: 36,
        comments: "OK 36",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Dos tableros fijos",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.7",
        name: "Salón SM-2.7",
        floor: 2,
        capacity: 36,
        countedSeats: 36,
        comments: "OK 36",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Dos tableros fijos",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.8",
        name: "Salón SM-2.8",
        floor: 2,
        capacity: 36,
        countedSeats: 39,
        comments: "unos 3 mas",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Dos tableros fijos",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "Cerca a la cancha",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.9",
        name: "Salón SM-2.9",
        floor: 2,
        capacity: 36,
        countedSeats: 35,
        comments: "unos 3 mas",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Dos tableros fijos",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.10",
        name: "Salón SM-2.10",
        floor: 2,
        capacity: 36,
        countedSeats: 36,
        comments: "OK 36",
        characteristic: "Plano-MesaMov-SillaMov (64)",
        type: "Plano",
        tableType: "Móvil Para 3 Personas",
        chairType: "Móvil",
        boardType: "Dos tableros fijos",
        equipment: "Proyector",
        outlets: "Por Mesa",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.11",
        name: "Salón SM-2.11",
        floor: 2,
        capacity: 50,
        countedSeats: 47,
        comments: "OK 50, pero hay 47 mesas y sillas",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "ok",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    },
    {
        code: "SM-2.12",
        name: "Salón SM-2.12",
        floor: 2,
        capacity: 24,
        countedSeats: 25,
        comments: "Deberia ser para 21",
        characteristic: "Plano-SillaUniveristaria (61)",
        type: "Plano",
        tableType: "Móvil Individual",
        chairType: "Móvil",
        boardType: "Fijo",
        equipment: "Proyector",
        outlets: "No Tiene",
        mobility: "Accesible",
        environment: "Muy pequeño",
        reservationContact: "Auto reservas  / Reservas Multimedios@",
        status: "En uso",
        usableForReservations: true
    }
];

const seedDatabase = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        await Auditorium.deleteMany({});
        await Auditorium.insertMany(auditoriumsData);
        console.log('✅ Base de datos poblada con auditorios actualizados');
    } catch (error) {
        console.error('❌ Error al poblar la base de datos:', error);
    } finally {
        mongoose.connection.close();
    }
};

// Ejecutar con: node utils/seedDatabase.js --run
if (process.argv[2] === '--run') {
    seedDatabase();
}

export default seedDatabase;